---
name: Text-xSV
version: 0.21
author: []
abstract: read character separated files
license: perl
resources:
  license: http://dev.perl.org/licenses/
provides:
  Text::xSV:
    file: lib/Text/xSV.pm
    version: 0.21
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
