--- #YAML:1.0
name: Text-xSV
version: 0.1
license: perl
distribution_type: module
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Text::xSV:
    file: lib/Text/xSV.pm
    version: 0.1
generated_by: Module::Build version 0.20
